tls:
  certificates:
    - certFile: /certs/nando-erp-server.crt
      keyFile: /certs/key.pem
  stores:
    default:
      defaultCertificate:
        certFile: /certs/nando-erp-server.crt
        keyFile: /certs/key.pem
